### ISSUE TITLE
Cannot connect to server 'https://gpt.pawan.krd/'

### ISSUE THREAD

**Issue by IvanKonov** [PawanOsman/ChatGPT.Net#11]
Trying to join the server all day today:
Cannot connect to server 'https://gpt.pawan.krd/'

![image](https://user-images.githubusercontent.com/20556427/216626926-2168619e-1d2a-46c4-8484-9a9628dd1096.png)

**Comment by IvanKonov** [comment]
Have you blocked me by IP address? Why was I able to connect via VPN? If yes, then why?

**Comment by PawanOsman** [comment]
dm me your IP in discord i will check if your IP is blocked or not

**Comment by IvanKonov** [comment]
Can you please tell me where can I find your Discord?

**Comment by dave-nikolas** [comment]
This is the link to his Discord server: https://discord.com/invite/VCdWGREsmd which can also be found in the README.md of the repository.
