### ISSUE TITLE
How to get SessionToken?

### ISSUE THREAD

**Issue by qcjxberin** [PawanOsman/ChatGPT.Net#12]
How to get SessionToken?

**Comment by dave-nikolas** [comment]
First, you need to open the ChatGPT website and log in. Then open the inspection menu, right-click inspect and go to the application tab, then cookies and there you will find the __Secure-next-auth.session-token. But you can also use the API key, which can be found here: https://platform.openai.com/account/api-keys.

**Comment by qcjxberin** [comment]
Can I use API keys to be context-sensitive?

**Comment by qcjxberin** [comment]
In addition, do you need to manually obtain the SessionToken every time, is there a way to obtain it automatically

**Comment by PawanOsman** [comment]
> In addition, do you need to manually obtain the SessionToken every time, is there a way to obtain it automatically

there are some libraries doing it but not reliable
session token can last for 7 days, you can renew it every 7 days
