### ISSUE TITLE
Unofficial unusable

### ISSUE THREAD

**Issue by HaoDong108** [PawanOsman/ChatGPT.Net#28]
at ChatGPTUnofficial.cs line 258
``` c#
  var client = new HttpClient();
        var request = new HttpRequestMessage
        {
            Method = HttpMethod.Post,
            RequestUri = new Uri($"{Config.BaseUrl}/backend-api/conversation"),
            Headers =
            {
                {"Authorization", $"Bearer {AccessToken}" }
            },
            Content = new StringContent(JsonConvert.SerializeObject(requestData))
            {
                Headers =
                {
                    ContentType = new MediaTypeHeaderValue("application/json")
                }
            }
        };
        var response = await client.SendAsync(request);

        response.EnsureSuccessStatusCode();
        var stream = await response.Content.ReadAsStreamAsync();
        var str = await new StreamReader(stream).ReadToEndAsync();  // always an empty string
```

**Comment by PawanOsman** [comment]
Currently auth endpoint is stopped working and its patched by OpenAI, we may remove the session-token and use access-token directly for the unofficial method

**Comment by lidiaparrilla** [comment]
Hi @PawanOsman, can you explain how the access token should be formated to use it? I am trying to set the field AccessToken from the ChatGptUnofficial to allow for the access token directly, but the ValidateToken method is returning the following error:

`The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.`

in line:
`var decodedPayload = Encoding.UTF8.GetString(Convert.FromBase64String(tokenPart));`

I wonder how I can use it in the meantime. I can also support you with the modification from session-token to access-token if you explain your strategy.
