### ISSUE TITLE
How to respone to client with webapi not console and less lag？ thank you

### ISSUE THREAD

**Issue by Smallthing** [PawanOsman/ChatGPT.Net#33]
is there ssr function in the sdk？

**Comment by PawanOsman** [comment]
Can you explain your question more?

**Comment by Smallthing** [comment]
sprry there is a typo
I mean make a webapi api with SSE sever side event to fast respone。。is this sdk include this method or I must make it myself

**Comment by Caulm** [comment]
Use `AskStream` method. @Smallthing 
If you are using the unofficial one, see my PR which fixes it.
