### ISSUE TITLE
questions with same conversationId are split

### ISSUE THREAD

**Issue by Caulm** [PawanOsman/ChatGPT.Net#6]
I've got a problem that AI always forgets the previous questions and answers, when I ask a new question.
I have set a `conversationId` when asking, and I'm not using the BrowserMode.
From the chat history in the browser, I find that the questions are split into multiple conversations. Only one question in each conversation.

Here‘s an example.
```
string conversationId = "group-78015"; //a string to distinguish users

var response1 = await chatGptClient.Ask("Explain quantum computing in simple terms", conversationId);
Console.WriteLine("response1: " + response1);

var response2 = await chatGptClient.Ask("Where can it be applied?", conversationId);
Console.WriteLine("response2: " + response2);
```
Console output
```
response1: Quantum computing is a type of computing ......

response2: Can you please clarify what you are asking about?
```
Chat history
![image](https://user-images.githubusercontent.com/40651411/210301169-25a2891d-d1b2-4373-a416-c6a790dada6c.png)
![image](https://user-images.githubusercontent.com/40651411/210301192-6944b3a5-35a1-42c8-8b2a-4526906416e2.png)

**Comment by Caulm** [comment]
![image](https://user-images.githubusercontent.com/40651411/210306262-6a8de5aa-30c0-463a-a48a-79e0e3c310a9.png)

**Comment by PawanOsman** [comment]
Yesterday I added another server to the pool and I fixed the message escaping issue, but after testing I forgot that I removed the conversation id from the payload, today I will update the server and it will be fixed

**Comment by Caulm** [comment]
okay, thanks.

**Comment by PawanOsman** [comment]
Fixed

**Comment by IvanKonov** [comment]
It's still relevant. AI forgets previous conversation
