### ISSUE TITLE
The way to use sessions is often disconnected or expired

### ISSUE THREAD

**Issue by qcjxberin** [PawanOsman/ChatGPT.Net#7]
The way to use sessions is often disconnected or expired

![image](https://user-images.githubusercontent.com/5792218/212476775-8d47b763-ff87-4f1e-9ef4-7a9f3fe93253.png)

**Comment by qcjxberin** [comment]
![image](https://user-images.githubusercontent.com/5792218/212476866-e0063241-f0b7-4e4c-b122-64e6cae1e3cb.png)

**Comment by PawanOsman** [comment]
Updated: Please update to the latest version

**Comment by qcjxberin** [comment]
OK,Tks

**Comment by qcjxberin** [comment]
![image](https://user-images.githubusercontent.com/5792218/212805789-89b05801-5d84-4e9f-9cbf-378f920b8ec4.png)

**Comment by PawanOsman** [comment]
Make sure your internet has access to the server. Perhaps you are behind a firewall that is blocking your connection to the server.

**Comment by qcjxberin** [comment]
![image](https://user-images.githubusercontent.com/5792218/213094653-e4eb3e52-3244-4cba-ae85-3a53071c6787.png)

**Comment by PawanOsman** [comment]
Looks like you have unstable connection, check your internet connection it must be stable, a single disconnection from your internet will disconnect the socket, try use a vpn or use a cloud vps to run your application
