### ISSUE TITLE
It's still relevant. AI forgets previous conversation (https://github.com/PawanOsman/ChatGPT.Net/issues/6)

### ISSUE THREAD

**Issue by IvanKonov** [PawanOsman/ChatGPT.Net#9]
It's still relevant. AI forgets previous conversation (https://github.com/PawanOsman/ChatGPT.Net/issues/6)

**Comment by PawanOsman** [comment]
can you provide a reproducible example

**Comment by hartmark** [comment]
+1 I have same problem, just run the following block twice. I expect the chat to stay in the same chat, but now I have two.


```

    var chatGpt = new ChatGpt(new ChatGptConfig
    {
        UseCache = true
    });
    await chatGpt.WaitForReady();
    string sessionToken =
        "xxxx";
    var chatGptClient = await chatGpt.CreateClient(new ChatGptClientConfig
    {
        SessionToken = sessionToken,
        AccountType = AccountType.Free
    });

    var response = await chatGptClient.Ask(args1[0], "auto-bot");
    Console.Error.WriteLine("Query time: " + stopwatch.Elapsed.Humanize(2));
    Console.WriteLine(response);
```

![image](https://user-images.githubusercontent.com/12826053/217120349-345f1b9e-3dc2-4ff2-8f43-2e1542570853.png)

**Comment by PawanOsman** [comment]
you need to run this part one time
> var chatGpt = new ChatGpt(new ChatGptConfig
>     {
>         UseCache = true
>     });
>     await chatGpt.WaitForReady();
>     string sessionToken =
>         "xxxx";
>     var chatGptClient = await chatGpt.CreateClient(new ChatGptClientConfig
>     {
>         SessionToken = sessionToken,
>         AccountType = AccountType.Free
>     });

then you can run this part as many as you want
>     var response = await chatGptClient.Ask(args1[0], "auto-bot");
>     Console.Error.WriteLine("Query time: " + stopwatch.Elapsed.Humanize(2));
>     Console.WriteLine(response);

**Comment by hartmark** [comment]
Thanks for reply, is it possible to run part 1 once I a dotnet-process and in another process reuse it?

**Comment by IvanKonov** [comment]
if the connection was lost, then calling the ask() method will restore it?

**Comment by PawanOsman** [comment]
> Thanks for reply, is it possible to run part 1 once I a dotnet-process and in another process reuse it?

no they must be in the same application
you can use the HTTP API example to create an API and use it anywhere

**Comment by PawanOsman** [comment]
> if the connection was lost, then calling the ask() method will restore it?

yes it will restore automatically
